#! /bin/sh


#Date:2019-07-08
#Description: rocketmq_Srv start controll


BIN='/opt/rocketmq/bin/mqnamesrv'
BINSTOP='/opt/rocketmq/bin/mqshutdown'
PID=`ps -ef|grep mqnamesrv|grep -v grep|awk '{printf $2}'`
LOG='/opt/rocketmq/logs/rocketmqlogs/namesrv.log'

case "$1" in
    start)
        echo -n "Starting rocketmq_Srv... "
        if [ "$PID" != "" ]; then
            echo "rocketmq_Srv (pid $PID) already running."
            exit 1
        fi
        sh $BIN -n IPADDR:9876 > $LOG &
        if [ "$?" != 0 ]; then
            echo " failed"
            exit 1
        else
            echo " done"
        fi
        ;;

    stop)
        echo -n "Stoping rocketmq_Srv... "
        if [ "$PID" = "" ]; then
            echo "rocketmq_Srv is not running."
            exit 1
        fi
        sh $BINSTOP namesrv
        sleep 3
        if [ "$?" != 0 ] ; then
            echo " stop failed."
        else
            echo " done"
        fi
        ;;

    status)
        if [ "$PID" != "" ]; then
            echo "rocketmq_Srv (pid $PID) is running..."
        else
            echo "rocketmq_Srv is stopped."
            exit 0
        fi
        ;;

    restart)
        $0 stop
        sleep 5
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;

esac